version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"